### ISSUE TITLE
Linked blog is apparently not there?

### ISSUE THREAD

**Issue by WillEhrendreich** [microsoft/Windows-AppConsult-Samples-DesktopBridge#6]
I was interested in seeing the initial blog post that was talking about the MvvmGenerator sample, and upon clicking the link to the blog I get a 404. [https://docs.microsoft.com/en-us/archive/blogs/appconsult/tag/desktop-bridge](https://docs.microsoft.com/en-us/archive/blogs/appconsult/tag/desktop-bridge)

**Comment by qmatteoq** [comment]
Thanks for heads up! We fixed the URL to redirect to the new blog. Unfortunately I checked and we never published a blog post on the topic, maybe @runceel can give you some pointers since he authored the sample.

**Comment by WillEhrendreich** [comment]
Thanks!

**Comment by runceel** [comment]
I had created MvvmGenerator sample 10 month ago. But this is not available on NuGet.
https://github.com/runceel/MvvmGenerator

Unfortunately, there is not any English article.

I recommend Fonderie.INPC.Generator package to generate implementation of INotifyPropertyChanged interface. This is available on NuGet, and the source code is also available on GitHub.
https://www.nuget.org/packages/Fonderie.INPC.Generator/

https://github.com/jeromelaban/fonderie
